# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TextureSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TextureSample
  pod 'Texture', '~> 3.0'
  pod 'RxSwift', '5.1'
  pod 'RxCocoa', '5.1'
  pod 'RxAlamofire', '~> 5.7.1'
  
  target 'TextureSampleTests' do
    inherit! :search_paths
    # Pods for testing
    
    pod 'RxBlocking', '5.1'
    pod 'RxTest', '5.1'
        
  end

  target 'TextureSampleUITests' do
    # Pods for testing
  end

end
