# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TextureSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TextureSample
  pod 'Texture', '~> 3.0'
  
  target 'TextureSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TextureSampleUITests' do
    # Pods for testing
  end

end
